spring:
  security:
    user:
      name: myUsername
      password: myPassword
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-017.cjdmzjfnvqzm.ap-northeast-2.rds.amazonaws.com/stackoverflow_017
    username: admin
    password: qordpsem017~
  sql:
    init:
      platform: mysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false

jwt:
  secret: 0687bd30a2a1cc4f69e46ca9cbdad76ceda5305b660886690db3eeb15f309a86  # Consider using environment variables
  expiration: 3600

server:
  port: 8080

logging:
  level:
    org:
      springframework: DEBUG
