spring:
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      platform: ${SPRING_SQL_INIT_PLATFORM}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

server:
  port: ${SERVER_PORT}

logging:
  level:
    org:
      springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}

    #hibernate:
    #  ddl-auto: create

